### ISSUE TITLE
HTTPS Not working @nielsole

### ISSUE THREAD

**Issue by Kishoreramesh07** [nielsole/kudos#2]

**Comment by Kishoreramesh07** [comment]
Your connection is not private
Attackers might be trying to steal your information from kudos.niels-ole.com (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

Help improve Safe Browsing by sending some system information and page content to Google. Privacy Policy

**Comment by nielsole** [comment]
works again.
